# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx512m -XX:MaxMetaspaceSize=256m
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

# Version of flipper SDK to use with React Native
FLIPPER_VERSION=0.182.0

# Use this property to specify which architecture you want to build.
# You can also override it from the CLI using
# ./gradlew <task> -PreactNativeArchitectures=x86_64
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Use this property to enable support to the new architecture.
# This will allow you to use TurboModules and the Fabric render in
# your application. You should enable this flag either if you want
# to write custom TurboModules/Fabric components OR use libraries that
# are providing them.
newArchEnabled=false

# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled=true

# API 'android.registerTransform' is obsolete.
# It will be removed in version 8.0 of the Android Gradle plugin.
# The Transform API is removed to improve build performance. Projects that use the
# Transform API force the Android Gradle plugin to use a less optimized flow for the
# build that can result in large regressions in build times. It?s also difficult to
# use the Transform API and combine it with other Gradle features; the replacement
# APIs aim to make it easier to extend the build without introducing performance or
# correctness issues.
#
# There is no single replacement for the Transform API?there are new, targeted
# APIs for each use case. All the replacement APIs are in the
# `androidComponents {}` block.
#
# The Transform API uses incremental APIs deprecated since Gradle 7.5. Please add
# `android.experimental.legacyTransform.forceNonIncremental=true` to
# `gradle.properties` to fix this issue. Note that this will run transforms
# non-incrementally and may have a build performance impact.
# For more information, see https://developer.android.com/studio/releases/gradle-plugin-api-updates#transform-api.
# To determine what is calling android.registerTransform, use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
android.experimental.legacyTransform.forceNonIncremental=true
